name: 🔨 Custom Build

on: 
  workflow_dispatch:
    inputs:
      # Inputs - Build settings
      versionName:
        description: "Version Name"
        type: string
        required: true
      nightly:
        description: "Nightly Build"
        type: boolean
        default: false

      # Inputs - Base Game repository
      gameRepositoryAuthor:
        description: "Base Game - Repository Author"
        default: "YARC-Official"
        type: string
      gameRepositoryName:
        description: "Base Game - Repository Name"
        default: "YARG"
        type: string
      gameRepositoryBranch:
        description: "Base Game - Repository Branch"
        default: "dev"
        type: string

      # Inputs - YARG.Core repository
      customCoreRepository:
        description: "Use custom YARG.Core repository"
        type: boolean
        default: false
      coreRepositoryAuthor:
        description: "YARG.Core - Repository Author"
        default: "YARC-Official"
        type: string
      coreRepositoryName:
        description: "YARG.Core - Repository Name"
        default: "YARG.Core"
        type: string
      coreRepositoryBranch:
        description: "YARG.Core - Repository Branch"
        default: "master"
        type: string
    

jobs:
  linux-builder:
    name: "🔨 Build - Linux"
    uses: ./.github/workflows/build-Linux.yml
    secrets: inherit
    with: 
      versionName: ${{ inputs.versionName }}
      nightly: ${{ inputs.nightly }}
      gameRepositoryAuthor: ${{ inputs.gameRepositoryAuthor }}
      gameRepositoryName: ${{ inputs.gameRepositoryName }}
      gameRepositoryBranch: ${{ inputs.gameRepositoryBranch }}
      customCoreRepository: ${{ inputs.customCoreRepository }}
      coreRepositoryAuthor: ${{ inputs.coreRepositoryAuthor }}
      coreRepositoryName: ${{ inputs.coreRepositoryName }}
      coreRepositoryBranch: ${{ inputs.coreRepositoryBranch }}

  mac-builder:
    name: "🔨 Build - MacOS"
    uses: ./.github/workflows/build-Mac.yml
    secrets: inherit
    with: 
      versionName: ${{ inputs.versionName }}
      nightly: ${{ inputs.nightly }}
      gameRepositoryAuthor: ${{ inputs.gameRepositoryAuthor }}
      gameRepositoryName: ${{ inputs.gameRepositoryName }}
      gameRepositoryBranch: ${{ inputs.gameRepositoryBranch }}
      customCoreRepository: ${{ inputs.customCoreRepository }}
      coreRepositoryAuthor: ${{ inputs.coreRepositoryAuthor }}
      coreRepositoryName: ${{ inputs.coreRepositoryName }}
      coreRepositoryBranch: ${{ inputs.coreRepositoryBranch }}

  windows-builder:
    name: "🔨 Build - Windows"
    uses: ./.github/workflows/build-Windows.yml
    secrets: inherit
    with: 
      versionName: ${{ inputs.versionName }}
      nightly: ${{ inputs.nightly }}
      gameRepositoryAuthor: ${{ inputs.gameRepositoryAuthor }}
      gameRepositoryName: ${{ inputs.gameRepositoryName }}
      gameRepositoryBranch: ${{ inputs.gameRepositoryBranch }}
      customCoreRepository: ${{ inputs.customCoreRepository }}
      coreRepositoryAuthor: ${{ inputs.coreRepositoryAuthor }}
      coreRepositoryName: ${{ inputs.coreRepositoryName }}
      coreRepositoryBranch: ${{ inputs.coreRepositoryBranch }}
